# /etc/hitch/hitch.conf
## Basic hitch config for use with Varnish and Acmetool
## https://github.com/varnish/hitch/blob/master/docs/configuration.md

# Listening
frontend = "[*]:443"
# Expand by passing to 'openssl ciphers'
ciphers  = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
prefer-server-ciphers = on

# Send traffic to the Varnish backend using the PROXY protocol
backend        = "[::1]:6086"
write-proxy-v2 = on

# List of PEM files, each with key, certificates and dhparams
pem-file = "/etc/letsencrypt/live/cache.seriesgui.de/hitch-bundle.pem"

# Enable TLS 1.0 (for Android 4.4)
# On Ubuntu 22.04 need to also lower SECLEVEL:
# /etc/ssl/openssl.cnf
# [system_default_sect]
# CipherString = DEFAULT:@SECLEVEL=0
# Use sslscan to verify configuration.
tls-protos = TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
