# /etc/systemd/system/varnish.service.d/override.conf
# edit with 'sudo systemctl edit varnish'
# overrides default varnish config, see systemctl cat varnish
[Unit]
After=network.target

# memory cache
# [Service]
# ExecStart=
# ExecStart=/usr/sbin/varnishd -a :80 -a '[::1]:6086,PROXY' -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m

# file cache
# `-a :80` to listen on port 80 as well for LetsEncrypt challenges.
# The `-S` parameter for varnishd is just a secret used to access its CLI interface.
# https://varnish-cache.org/docs/trunk/users-guide/run_security.html#cli-interface-authentication
[Service]
ExecStart=
ExecStart=/usr/sbin/varnishd \
          -j unix,user=vcache \
          -F \
          -a :80 \
          -a '[::1]:6086,PROXY' \
          -T localhost:6082 \
          -f /etc/varnish/default.vcl \
          -S /etc/varnish/secret \
          -s file,/var/lib/varnish/varnish_storage.bin,40G
