# /etc/systemd/system/varnish.service.d/override.conf
# edit with 'sudo systemctl edit varnish'
# overrides default varnish config, see 'systemctl cat varnish'

[Unit]
# Start after/stop before network management stack is up/down (but no need for network to be "up")
# https://systemd.io/NETWORK_ONLINE/
After=network.target

# Do not allow automatic start if started for 5 times in the last 10 seconds
# Values are identical to suggested default values (DefaultStartLimitIntervalSec and DefaultStartLimitBurst)
# https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html
StartLimitIntervalSec=10
StartLimitBurst=5

[Service]
# Clear ExecStart from default config
ExecStart=

# memory cache
# ExecStart=/usr/sbin/varnishd -a :80 -a '[::1]:6086,PROXY' -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m

# file cache
# `-a :80` to listen on port 80 as well for LetsEncrypt challenges.
# The `-S` parameter for varnishd is just a secret used to access its CLI interface.
# https://varnish-cache.org/docs/trunk/users-guide/run_security.html#cli-interface-authentication
ExecStart=/usr/sbin/varnishd \
          -j unix,user=vcache \
          -F \
          -a :80 \
          -a '[::1]:6086,PROXY' \
          -T localhost:6082 \
          -f /etc/varnish/default.vcl \
          -S /etc/varnish/secret \
          -s file,/var/lib/varnish/varnish_storage.bin,40G

# Restart on unclean exit
# https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html
Restart=on-failure
